version: '3.9'

services:
  # ================================================================
  # 1. EUREKA SERVER
  # ================================================================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - bank-network

  # ================================================================
  # 2. API GATEWAY
  # ================================================================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - bank-network

  # ================================================================
  # 3. MYSQL DATABASE
  # ================================================================
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    networks:
      - bank-network
    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ================================================================
  # 4. AUTH SERVICE
  # ================================================================
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - bank-network

  # ================================================================
  # 5. USER SERVICE
  # ================================================================
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8085:8085"
    networks:
      - bank-network

  # ================================================================
  # 6. ACCOUNT SERVICE
  # ================================================================
  account-service:
    build: ./account-service
    container_name: account-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      user-service:
        condition: service_started
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/account_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - bank-network

  # ================================================================
  # 7. TRANSACTION SERVICE
  # ================================================================
  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      account-service:
        condition: service_started
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/transaction_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8083"
    networks:
      - bank-network

  # ================================================================
  # 8. NOTIFICATION SERVICE
  # ================================================================
  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      SERVER_PORT: 8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: phamtuna785aa@gmail.com
      SPRING_MAIL_PASSWORD: xvrr oogz gvel oslm
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: transaction-events
    ports:
      - "8084:8084"
    networks:
      - bank-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


# ================================================================
# VOLUMES & NETWORK
# ================================================================
volumes:
  mysql_data:

networks:
  bank-network:
    driver: bridge
